<?php

/**
 * @file
 * Contains redirection_anonymous_d8.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function redirection_anonymous_d8_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the redirection_anonymous_d8 module.
    case 'help.page.redirection_anonymous_d8':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Redirection obligatoire sur la page d&#039;accueil') . '</p>';
      return $output;

    default:
  }
}
