<?php

function certification_d8_form_alter(&$form, &$form_state, $form_id) {
	//kint($form_id);

  if(isset($form['sort_order'])){
	$form['sort_order']['#type'] = FALSE;
  }

	$current_user_name = \Drupal::currentUser()->getUsername();
			
	if($form_id == 'node_certification_d8_form' || $form_id == 'node_certification_d8_edit_form'){

	//kint($form);
		 
			$userRole = \Drupal::currentUser()->getRoles();
			//kint($userRole);


		if (in_array('administrator', $userRole) ) {
		  array_unshift($form['actions']['submit']['#submit'],'sub_author');
		}

		// Cache le menu  en ajout et modification et lui attribuer le nom de l'utilisateur par default
		$title_widget = &$form['title']['widget'][0];
		$default = (!empty($title_widget['value']['#default_value'])? $title_widget['value']['#default_value'] :$current_user_name);
		$title_widget['value']['#default_value'] = $default;
		$title_widget['value']['#type'] = 'value';
		$title_widget['value']['#required'] = FALSE;
		$title_widget['revision_information']['#access'] = FALSE;
		$form['title']['#access'] = FALSE;
		$form['actions']['preview']['#access']    = FALSE;
		$form['revision']['#access'] = FALSE;
		$form['revision_information']['#access'] = FALSE;

		// restriction aux dates passées uniquement
		// if(isset($form['field_date_passage'])){
		// 	$form['field_date_passage'] = array(
		// 		'#type'           => 'date',
		// 		'#title'          => t('Date de passage'),
		// 		'#min'            => '2000-01-01',
		// 		'#max'            => date('Y-m-d'),
		// 		'#default_value'  => date('Y-m-d'),
		// 		'#require'        => 'true'  
		// 	);
		// }
	}
}

function sub_author($form, $form_state){

	$values      	= $form_state->getUserInput();
	$utilisateur 	= $values['uid'][0]['target_id'];
	$author 	 	= trim(explode('(',$utilisateur)[0]);
	$form_state->setValue('title',[['value'=>$author]]);
}


function certification_d8_field_widget_form_alter(&$element, \Drupal\Core\Form\FormStateInterface $form_state, $context) {

}


function certification_d8_user_presave(Drupal\user\Entity\User $user) {
  if ($user->isNew() && !$user->hasRole('drupalien')) {
    $admin = FALSE;
    if (!$admin) {
      $user->addRole('drupalien');
    }
  }
}

// function certification_page_attachments(array &$page){
// 	$routeName = \Drupal::routeMatch()->getRouteName();
// 	//kint($routeName);die();
// 	//kint($page);die();
// 	if ($routeName == 'node.add') {
// 		$page['#attached']['library'][] = 'certification/certification';
// 	}
// }